### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by dangell7**
Add start commands to docker-compose.yml

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [x] Documentation Updates
- [ ] Release

### CODE REVIEW

**Review by dino-rodriguez — APPROVED** [review]
Great comment! Important to have usage information readily visible.

**Comment by dangell7** [comment]
Honestly its just personal preference.. I work with 3 docker-compose.yml files for production so I like to have the documentation of how to run each separate compose file in standalone env's....

Also, the 2 commands worked for me and whatever you had in the documentation didn't work so I was just wanting to help others.

**Review by payupsucker — COMMENTED** [review]
Hi

**Comment by GitesParti343** [comment]
#691

**Comment by GitesParti343** [comment]
> Add start commands to docker-compose.yml
> 
> ## High Level Overview of Change
> 
> 
> 
> ### Context of Change
> 
> 
> 
> ### Type of Change
> 
> 
> 
> - [ ] Bug fix (non-breaking change which fixes an issue)
> - [ ] New feature (non-breaking change which adds functionality)
> - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> - [ ] Refactor (non-breaking change that only restructures code)
> - [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
> - [x] Documentation Updates
> - [ ] Release
> 
> ## Before / After
> 
> 
> 
> ## Test Plan
> 
> 
> 
> 
> 

#649

**Comment by GitesParti343** [comment]
#691

**Comment by baldFun50** [comment]
patch

**Pull request merged**
