### PR TITLE
Update config.ts

### PR DESCRIPTION
**Pull request by VIRTUECOIN**
### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [x] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [x] Release

### CODE REVIEW

**Comment by VIRTUECOIN** [comment]
Was this done correctly?

**Comment by hbergren** [comment]
You shouldn't need to change that variable. This should get automatically set by the first HTTP request that hits the Public API of your PayID server. If your server is actually on that domain, that should happen automatically.

**Comment by VIRTUECOIN** [comment]
What ya mean

**Comment by dino-rodriguez** [comment]
@VIRTUECOIN When you set up a PayID server, it will automatically get your domain from the first request made to the server, so you don't need to set this value unless you want to specify a different domain than the one your server is running.

This is also a configuration setting that should be changed locally in your server, as opposed to in this repository since it is a change that is personal to VirtueCoin.

Does that make sense?

**Comment by VIRTUECOIN** [comment]
Im a newbie it kinda makes sense could you help me get this going I want to
airdrop virtuecoin also

**Pull request closed without merging**
